name: Korx.Cycler
author: korx
category: Widgets
current: 0.3
tags: [cycler, css3, html5, animation, slider, carousel, slideshow, gallery]
docs: https://github.com/korx/Korx.Cycler/blob/master/README.md
demo: http://korx.github.com/Korx.Cycler/Demo/