name: Korx.Cycler
author: korx
category: Widgets
current: 0.1
tags: [cycler, css3, slideshow, carousel, animation, gallery, html5]
docs: https://github.com/korx/Korx.Cycler/blob/master/README.md
demo: http://jsfiddle.net/korx/hgjem/